default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: peter-mcburney_development

test:
  <<: *default
  database: peter-mcburney_test

production:
 <<: *default
 database: peter-mcburney_development
 username: andrewmcburney
 password: Be@r14
